# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-GA-Gramadoir
version:      0.50
version_from: lib/Lingua/GA/Gramadoir.pm
installdirs:  site
requires:
    Carp:                          0
    Encode:                        0
    ExtUtils::MakeMaker:           6.03
    File::Spec:                    0.83
    Getopt::Long:                  2.32
    Memoize:                       0.52
    Memoize::ExpireLRU:            0
    Storable:                      2.04
    String::Approx:                3.19
    Term::ANSIColor:               1.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
